# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-13 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_auto_20180913_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partneraddress',
            name='line2',
        ),
        migrations.AlterField(
            model_name='partneraddress',
            name='line1',
            field=models.CharField(help_text='Preferrably your street address, e.g.( Abeka, Mukose Street)', max_length=255, verbose_name='Your Address'),
        ),
    ]
