# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-09-13 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobilemoney', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileMoneyTransaction',
        ),
    ]
